# Generated by Django 5.2.8 on 2025-12-10 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrix', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='agendamento',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='planoalimentar',
            name='consulta',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
        migrations.RemoveField(
            model_name='nutricionista',
            name='data_nascimento',
        ),
        migrations.AddField(
            model_name='cliente',
            name='altura',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='condicao_agendamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_agendamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='google_meet_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nutricionista',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='nutrix.nutricionista'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='peso',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='crn',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Agendamento',
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
        migrations.DeleteModel(
            name='PlanoAlimentar',
        ),
    ]
