# Generated by Django 5.2.8 on 2025-12-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrix', '0002_remove_consulta_agendamento_remove_consulta_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
