# Generated by Django 5.2.8 on 2025-12-10 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrix', '0003_cliente_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutricionista',
            name='crn',
        ),
        migrations.RemoveField(
            model_name='nutricionista',
            name='telefone',
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nutricionista',
            name='registro',
            field=models.CharField(default='CRN-0000', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='altura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
